export const CLIENT_ADDED = 'CLIENT_ADDED'
export const CLIENTS_ADDING_LOADING = 'CLIENTS_ADDING_LOADING'
export const CLIENTS_EDITING_LOADING = 'CLIENTS_EDITING_LOADING'
export const CLIENT_EDITED = 'CLIENT_EDITED'

export const CLIENTS_LOADING = 'CLIENTS_LOADING'
export const CLIENTS_LOADED = 'CLIENTS_LOADED'
